// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQCHZxYOglksYSG99uQUmu1St8gXcjLm4',
    appId: '1:217944956871:web:4e29405d697e3819bd83e2',
    messagingSenderId: '217944956871',
    projectId: 'spotifi2050',
    authDomain: 'spotifi2050.firebaseapp.com',
    storageBucket: 'spotifi2050.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR2LmYgia203ESq388MNcEV28CXXP1lrE',
    appId: '1:217944956871:android:21b8003e85f9fdc9bd83e2',
    messagingSenderId: '217944956871',
    projectId: 'spotifi2050',
    storageBucket: 'spotifi2050.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7BwdkyF4mxPTgxQYGZsUi18BfyKNO4EA',
    appId: '1:217944956871:ios:dbebd586071fbbbabd83e2',
    messagingSenderId: '217944956871',
    projectId: 'spotifi2050',
    storageBucket: 'spotifi2050.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7BwdkyF4mxPTgxQYGZsUi18BfyKNO4EA',
    appId: '1:217944956871:ios:dbebd586071fbbbabd83e2',
    messagingSenderId: '217944956871',
    projectId: 'spotifi2050',
    storageBucket: 'spotifi2050.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQCHZxYOglksYSG99uQUmu1St8gXcjLm4',
    appId: '1:217944956871:web:f6c7aefde050381abd83e2',
    messagingSenderId: '217944956871',
    projectId: 'spotifi2050',
    authDomain: 'spotifi2050.firebaseapp.com',
    storageBucket: 'spotifi2050.appspot.com',
  );
}
